using ReportService as service from '../../../srv/ReportService';
annotate service.SalesOrderCreate with @(
    UI: {
        HeaderInfo: {
            Title: { $Type: 'UI.DataField', Value: PIOrder },
            Description: { $Type: 'UI.DataField', Value: PIOrderItem },
            TypeName: '销售订单创建表',
            TypeNamePlural: '销售订单创建列表'
        },
        SelectionFields: [PIOrder,SalesOrderType,SalesOrganization,Customer,Material,code,zrfc_logid,zdfjy],
        LineItem: [
            { $Type: 'UI.DataField', Label: 'PI单号', Value: PIOrder },
            { $Type: 'UI.DataField', Label: 'PI单行号', Value: PIOrderItem },
            { $Type: 'UI.DataField', Label: '销售订单类型', Value: SalesOrderType },
            { $Type: 'UI.DataField', Label: '销售组织', Value: SalesOrganization },
            { $Type: 'UI.DataField', Label: '分销渠道', Value: DistributionChannel },
            { $Type: 'UI.DataField', Label: '产品组', Value: OrganizationDivision },
            { $Type: 'UI.DataField', Label: '销售办公室', Value: SalesOffice },
            { $Type: 'UI.DataField', Label: '销售组', Value: SalesGroup },
            { $Type: 'UI.DataField', Label: '销售地区', Value: SalesDistrict },
            { $Type: 'UI.DataField', Label: '客户参考编号', Value: PurchaseOrderByCustomer },
            { $Type: 'UI.DataField', Label: '客户参考日期', Value: CustomerPurchaseOrderDate },
            { $Type: 'UI.DataField', Label: '凭证币别', Value: TransactionCurrency },
            { $Type: 'UI.DataField', Label: '订单原因', Value: SDDocumentReason },
            { $Type: 'UI.DataField', Label: '请求交货日期', Value: RequestedDeliveryDate },
            { $Type: 'UI.DataField', Label: '客户科目分配组', Value: CustomerAccountAssignmentGroup },
            { $Type: 'UI.DataField', Label: '国际贸易条款分类', Value: IncotermsClassification },
            { $Type: 'UI.DataField', Label: '国际贸易条款地点1', Value: IncotermsLocation1 },
            { $Type: 'UI.DataField', Label: '客户税分类1', Value: CustomerTaxClassification1 },
            { $Type: 'UI.DataField', Label: '客户付款条件', Value: CustomerPaymentTerms },
            { $Type: 'UI.DataField', Label: '销售订单抬头文本备注', Value: Remark },
            { $Type: 'UI.DataField', Label: '箱唛要求', Value: YY1_FD_XMYQ },
            { $Type: 'UI.DataField', Label: '打包方式', Value: YY1_FD_DBFS },
            { $Type: 'UI.DataField', Label: '发货要求', Value: YY1_FD_FHYQ },
            { $Type: 'UI.DataField', Label: '付款国', Value: YY1_FD_FKG },
            { $Type: 'UI.DataField', Label: '结算方式', Value: YY1_FD_JSFS },
            { $Type: 'UI.DataField', Label: '平台', Value: YY1_FD_PT },
            { $Type: 'UI.DataField', Label: '是否报关', Value: YY1_FD_SFBG },
            { $Type: 'UI.DataField', Label: '是否回单', Value: YY1_FD_SFHD },
            { $Type: 'UI.DataField', Label: '条码标签', Value: YY1_FD_TMBQ },
            { $Type: 'UI.DataField', Label: '运抵国', Value: YY1_FD_YDG },
            { $Type: 'UI.DataField', Label: '运输方式', Value: YY1_FD_YSFS },
            { $Type: 'UI.DataField', Label: '粘贴美文纸', Value: YY1_FD_ZTMWZ },
            { $Type: 'UI.DataField', Label: '账户(下单店铺)', Value: YY1_FD_ZH },
            { $Type: 'UI.DataField', Label: '多方交易ID', Value: YY1_FD_ZDFJY },
            { $Type: 'UI.DataField', Label: '审批联络函号', Value: YY1_FD_SPLLHH },
            { $Type: 'UI.DataField', Label: '箱唛资料', Value: YY1_FD_XMZL },
            { $Type: 'UI.DataField', Label: '销售订单行项目类别', Value: SalesOrderItemCategory },
            { $Type: 'UI.DataField', Label: '物料号', Value: Material },
            { $Type: 'UI.DataField', Label: '客户物料编号', Value: MaterialByCustomer },
            { $Type: 'UI.DataField', Label: '数量', Value: RequestedQuantity },
            { $Type: 'UI.DataField', Label: '单位', Value: RequestedQuantityUnit },
            { $Type: 'UI.DataField', Label: '工厂', Value: ProductionPlant },
            { $Type: 'UI.DataField', Label: '库存地点', Value: StorageLocation },
            { $Type: 'UI.DataField', Label: '销售订单行项目文本备注', Value: ItemRemark },
            { $Type: 'UI.DataField', Label: '客户采购订单行项目', Value: PurchaseOrderByShipToParty },
            { $Type: 'UI.DataField', Label: '产品税分类', Value: ProductTaxClassification1 },
            { $Type: 'UI.DataField', Label: '销售凭证拒绝原因', Value: SalesDocumentRjcnReason },
            { $Type: 'UI.DataField', Label: 'FNSKU/快递袋编码', Value: YY1_FD_FNSKU },
            { $Type: 'UI.DataField', Label: '客户SKU', Value: YY1_FD_SKU },
            { $Type: 'UI.DataField', Label: '定制卡板', Value: YY1_FD_DZKB },
            { $Type: 'UI.DataField', Label: '采购单价', Value: PurchasePrice },
            { $Type: 'UI.DataField', Label: 'ZB01价格', Value: ZB01_Value },
            { $Type: 'UI.DataField', Label: 'ZB01价格单位', Value: ZB01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB01数量单位', Value: ZB01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB02价格', Value: ZB02_Value },
            { $Type: 'UI.DataField', Label: 'ZB02价格单位', Value: ZB02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB02数量单位', Value: ZB02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB03价格', Value: ZB03_Value },
            { $Type: 'UI.DataField', Label: 'ZB03价格单位', Value: ZB03_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB03数量单位', Value: ZB03_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB04价格', Value: ZB04_Value },
            { $Type: 'UI.DataField', Label: 'ZB04价格单位', Value: ZB04_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB04数量单位', Value: ZB04_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC01价格', Value: ZC01_Value },
            { $Type: 'UI.DataField', Label: 'ZC01价格单位', Value: ZC01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC01数量单位', Value: ZC01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC02价格', Value: ZC02_Value },
            { $Type: 'UI.DataField', Label: 'ZC02价格单位', Value: ZC02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC02数量单位', Value: ZC02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZP00价格', Value: ZP00_Value },
            { $Type: 'UI.DataField', Label: 'ZP00价格单位', Value: ZP00_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZP00数量单位', Value: ZP00_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: '合作伙伴功能', Value: PartnerFunction },
            { $Type: 'UI.DataField', Label: '合作伙伴编号', Value: Customer },
            { $Type: 'UI.DataField', Label: '生产开始日期', Value: ProductionStartDate },
            { $Type: 'UI.DataField', Label: '交货日期', Value: ConfirmedDeliveryDate },
            { $Type: 'UI.DataField', Label: '订单确认数量', Value: ScheduleLineOrderQuantity },
            { $Type: 'UI.DataField', Label: '业务流程ID', Value: zrfcid },
            { $Type: 'UI.DataField', Label: '多步ID', Value: zrfc_logid },
            { $Type: 'UI.DataField', Label: '多方交易类型ID', Value: zdfjy },
            { $Type: 'UI.DataField', Label: '消息状态', Value: code },
            { $Type: 'UI.DataField', Label: '消息文本', Value: message },
        ],
        Identification: [
            { $Type: 'UI.DataField', Label: 'PI单号', Value: PIOrder },
            { $Type: 'UI.DataField', Label: 'PI单行号', Value: PIOrderItem },
            { $Type: 'UI.DataField', Label: '销售订单类型', Value: SalesOrderType },
            { $Type: 'UI.DataField', Label: '销售组织', Value: SalesOrganization },
            { $Type: 'UI.DataField', Label: '分销渠道', Value: DistributionChannel },
            { $Type: 'UI.DataField', Label: '产品组', Value: OrganizationDivision },
            { $Type: 'UI.DataField', Label: '销售办公室', Value: SalesOffice },
            { $Type: 'UI.DataField', Label: '销售组', Value: SalesGroup },
            { $Type: 'UI.DataField', Label: '销售地区', Value: SalesDistrict },
            { $Type: 'UI.DataField', Label: '客户参考编号', Value: PurchaseOrderByCustomer },
            { $Type: 'UI.DataField', Label: '客户参考日期', Value: CustomerPurchaseOrderDate },
            { $Type: 'UI.DataField', Label: '凭证币别', Value: TransactionCurrency },
            { $Type: 'UI.DataField', Label: '订单原因', Value: SDDocumentReason },
            { $Type: 'UI.DataField', Label: '请求交货日期', Value: RequestedDeliveryDate },
            { $Type: 'UI.DataField', Label: '客户科目分配组', Value: CustomerAccountAssignmentGroup },
            { $Type: 'UI.DataField', Label: '国际贸易条款分类', Value: IncotermsClassification },
            { $Type: 'UI.DataField', Label: '国际贸易条款地点1', Value: IncotermsLocation1 },
            { $Type: 'UI.DataField', Label: '客户税分类1', Value: CustomerTaxClassification1 },
            { $Type: 'UI.DataField', Label: '客户付款条件', Value: CustomerPaymentTerms },
            { $Type: 'UI.DataField', Label: '销售订单抬头文本备注', Value: Remark },
            { $Type: 'UI.DataField', Label: '箱唛要求', Value: YY1_FD_XMYQ },
            { $Type: 'UI.DataField', Label: '打包方式', Value: YY1_FD_DBFS },
            { $Type: 'UI.DataField', Label: '发货要求', Value: YY1_FD_FHYQ },
            { $Type: 'UI.DataField', Label: '付款国', Value: YY1_FD_FKG },
            { $Type: 'UI.DataField', Label: '结算方式', Value: YY1_FD_JSFS },
            { $Type: 'UI.DataField', Label: '平台', Value: YY1_FD_PT },
            { $Type: 'UI.DataField', Label: '是否报关', Value: YY1_FD_SFBG },
            { $Type: 'UI.DataField', Label: '是否回单', Value: YY1_FD_SFHD },
            { $Type: 'UI.DataField', Label: '条码标签', Value: YY1_FD_TMBQ },
            { $Type: 'UI.DataField', Label: '运抵国', Value: YY1_FD_YDG },
            { $Type: 'UI.DataField', Label: '运输方式', Value: YY1_FD_YSFS },
            { $Type: 'UI.DataField', Label: '粘贴美文纸', Value: YY1_FD_ZTMWZ },
            { $Type: 'UI.DataField', Label: '账户(下单店铺)', Value: YY1_FD_ZH },
            { $Type: 'UI.DataField', Label: '多方交易ID', Value: YY1_FD_ZDFJY },
            { $Type: 'UI.DataField', Label: '审批联络函号', Value: YY1_FD_SPLLHH },
            { $Type: 'UI.DataField', Label: '箱唛资料', Value: YY1_FD_XMZL },
            { $Type: 'UI.DataField', Label: '销售订单行项目类别', Value: SalesOrderItemCategory },
            { $Type: 'UI.DataField', Label: '物料号', Value: Material },
            { $Type: 'UI.DataField', Label: '客户物料编号', Value: MaterialByCustomer },
            { $Type: 'UI.DataField', Label: '数量', Value: RequestedQuantity },
            { $Type: 'UI.DataField', Label: '单位', Value: RequestedQuantityUnit },
            { $Type: 'UI.DataField', Label: '工厂', Value: ProductionPlant },
            { $Type: 'UI.DataField', Label: '库存地点', Value: StorageLocation },
            { $Type: 'UI.DataField', Label: '销售订单行项目文本备注', Value: ItemRemark },
            { $Type: 'UI.DataField', Label: '客户采购订单行项目', Value: PurchaseOrderByShipToParty },
            { $Type: 'UI.DataField', Label: '产品税分类', Value: ProductTaxClassification1 },
            { $Type: 'UI.DataField', Label: '销售凭证拒绝原因', Value: SalesDocumentRjcnReason },
            { $Type: 'UI.DataField', Label: 'FNSKU/快递袋编码', Value: YY1_FD_FNSKU },
            { $Type: 'UI.DataField', Label: '客户SKU', Value: YY1_FD_SKU },
            { $Type: 'UI.DataField', Label: '定制卡板', Value: YY1_FD_DZKB },
            { $Type: 'UI.DataField', Label: '采购单价', Value: PurchasePrice },
            { $Type: 'UI.DataField', Label: 'ZB01价格', Value: ZB01_Value },
            { $Type: 'UI.DataField', Label: 'ZB01价格单位', Value: ZB01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB01数量单位', Value: ZB01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB02价格', Value: ZB02_Value },
            { $Type: 'UI.DataField', Label: 'ZB02价格单位', Value: ZB02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB02数量单位', Value: ZB02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB03价格', Value: ZB03_Value },
            { $Type: 'UI.DataField', Label: 'ZB03价格单位', Value: ZB03_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB03数量单位', Value: ZB03_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB04价格', Value: ZB04_Value },
            { $Type: 'UI.DataField', Label: 'ZB04价格单位', Value: ZB04_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB04数量单位', Value: ZB04_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC01价格', Value: ZC01_Value },
            { $Type: 'UI.DataField', Label: 'ZC01价格单位', Value: ZC01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC01数量单位', Value: ZC01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC02价格', Value: ZC02_Value },
            { $Type: 'UI.DataField', Label: 'ZC02价格单位', Value: ZC02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC02数量单位', Value: ZC02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZP00价格', Value: ZP00_Value },
            { $Type: 'UI.DataField', Label: 'ZP00价格单位', Value: ZP00_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZP00数量单位', Value: ZP00_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: '合作伙伴功能', Value: PartnerFunction },
            { $Type: 'UI.DataField', Label: '合作伙伴编号', Value: Customer },
            { $Type: 'UI.DataField', Label: '生产开始日期', Value: ProductionStartDate },
            { $Type: 'UI.DataField', Label: '交货日期', Value: ConfirmedDeliveryDate },
            { $Type: 'UI.DataField', Label: '订单确认数量', Value: ScheduleLineOrderQuantity },
            { $Type: 'UI.DataField', Label: '业务流程ID', Value: zrfcid },
            { $Type: 'UI.DataField', Label: '多步ID', Value: zrfc_logid },
            { $Type: 'UI.DataField', Label: '多方交易类型ID', Value: zdfjy },
            { $Type: 'UI.DataField', Label: '消息状态', Value: code },
            { $Type: 'UI.DataField', Label: '消息文本', Value: message },
        ],
        Facets: [
            { $Type: 'UI.ReferenceFacet', Label: '基本信息', Target: '@UI.Identification' }
        ]
    }
);