using ReportService as service from '../../../srv/ReportService';
annotate service.SalesOrderChange with @(
    UI: {
        HeaderInfo: {
            Title: { $Type: 'UI.DataField', Value: PIOrder },
            Description: { $Type: 'UI.DataField', Value: PIOrderItem },
            TypeName: '销售订单修改表',
            TypeNamePlural: '销售订单修改列表'
        },
        SelectionFields: [PIOrder, Material, ProductionPlant,code,zrfc_logid,zdfjy],
        LineItem: [
            { $Type: 'UI.DataField', Label: 'PI单号', Value: PIOrder },
            { $Type: 'UI.DataField', Label: 'PI单行号', Value: PIOrderItem },
            { $Type: 'UI.DataField', Label: '销售订单行项目类别', Value: SalesOrderItemCategory },
            { $Type: 'UI.DataField', Label: '物料号', Value: Material },
            { $Type: 'UI.DataField', Label: '客户物料号', Value: MaterialByCustomer },
            { $Type: 'UI.DataField', Label: '请求数量', Value: RequestedQuantity },
            { $Type: 'UI.DataField', Label: '请求数量单位', Value: RequestedQuantityUnit },
            { $Type: 'UI.DataField', Label: '生产工厂', Value: ProductionPlant },
            { $Type: 'UI.DataField', Label: '库存地点', Value: StorageLocation },
            { $Type: 'UI.DataField', Label: '采购价格', Value: PurchasePrice },
            { $Type: 'UI.DataField', Label: 'ZB01条件值', Value: ZB01_Value },
            { $Type: 'UI.DataField', Label: 'ZB01货币代码', Value: ZB01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB01计量单位', Value: ZB01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB02条件值', Value: ZB02_Value },
            { $Type: 'UI.DataField', Label: 'ZB02货币代码', Value: ZB02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB02计量单位', Value: ZB02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB03条件值', Value: ZB03_Value },
            { $Type: 'UI.DataField', Label: 'ZB03货币代码', Value: ZB03_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB03计量单位', Value: ZB03_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB04条件值', Value: ZB04_Value },
            { $Type: 'UI.DataField', Label: 'ZB04货币代码', Value: ZB04_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB04计量单位', Value: ZB04_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC01条件值', Value: ZC01_Value },
            { $Type: 'UI.DataField', Label: 'ZC01货币代码', Value: ZC01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC01计量单位', Value: ZC01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC02条件值', Value: ZC02_Value },
            { $Type: 'UI.DataField', Label: 'ZC02货币代码', Value: ZC02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC02计量单位', Value: ZC02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZP00条件值', Value: ZP00_Value },
            { $Type: 'UI.DataField', Label: 'ZP00货币代码', Value: ZP00_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZP00计量单位', Value: ZP00_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'FNSKU', Value: YY1_FD_FNSKU },
            { $Type: 'UI.DataField', Label: 'SKU', Value: YY1_FD_SKU },
            { $Type: 'UI.DataField', Label: '对账口径', Value: YY1_FD_DZKB },
            { $Type: 'UI.DataField', Label: '生产开始日期', Value: ProductionStartDate },
            { $Type: 'UI.DataField', Label: '确认交货日期', Value: ConfirmedDeliveryDate },
            { $Type: 'UI.DataField', Label: '计划行订单数量', Value: ScheduleLineOrderQuantity },
            { $Type: 'UI.DataField', Label: '销售凭证拒绝原因', Value: SalesDocumentRjcnReason },
            { $Type: 'UI.DataField', Label: '业务流程ID', Value: zrfcid },
            { $Type: 'UI.DataField', Label: '多步ID', Value: zrfc_logid },
            { $Type: 'UI.DataField', Label: '多方交易类型ID', Value: zdfjy },
            { $Type: 'UI.DataField', Label: '消息状态', Value: code },
            { $Type: 'UI.DataField', Label: '消息文本', Value: message },
        ],
        Identification: [
            { $Type: 'UI.DataField', Label: 'PI单号', Value: PIOrder },
            { $Type: 'UI.DataField', Label: 'PI单行号', Value: PIOrderItem },
            { $Type: 'UI.DataField', Label: '销售订单行项目类别', Value: SalesOrderItemCategory },
            { $Type: 'UI.DataField', Label: '物料号', Value: Material },
            { $Type: 'UI.DataField', Label: '客户物料号', Value: MaterialByCustomer },
            { $Type: 'UI.DataField', Label: '请求数量', Value: RequestedQuantity },
            { $Type: 'UI.DataField', Label: '请求数量单位', Value: RequestedQuantityUnit },
            { $Type: 'UI.DataField', Label: '生产工厂', Value: ProductionPlant },
            { $Type: 'UI.DataField', Label: '库存地点', Value: StorageLocation },
            { $Type: 'UI.DataField', Label: '采购价格', Value: PurchasePrice },
            { $Type: 'UI.DataField', Label: 'ZB01条件值', Value: ZB01_Value },
            { $Type: 'UI.DataField', Label: 'ZB01货币代码', Value: ZB01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB01计量单位', Value: ZB01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB02条件值', Value: ZB02_Value },
            { $Type: 'UI.DataField', Label: 'ZB02货币代码', Value: ZB02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB02计量单位', Value: ZB02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB03条件值', Value: ZB03_Value },
            { $Type: 'UI.DataField', Label: 'ZB03货币代码', Value: ZB03_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB03计量单位', Value: ZB03_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZB04条件值', Value: ZB04_Value },
            { $Type: 'UI.DataField', Label: 'ZB04货币代码', Value: ZB04_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZB04计量单位', Value: ZB04_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC01条件值', Value: ZC01_Value },
            { $Type: 'UI.DataField', Label: 'ZC01货币代码', Value: ZC01_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC01计量单位', Value: ZC01_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZC02条件值', Value: ZC02_Value },
            { $Type: 'UI.DataField', Label: 'ZC02货币代码', Value: ZC02_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZC02计量单位', Value: ZC02_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'ZP00条件值', Value: ZP00_Value },
            { $Type: 'UI.DataField', Label: 'ZP00货币代码', Value: ZP00_CurrencyCode },
            { $Type: 'UI.DataField', Label: 'ZP00计量单位', Value: ZP00_UnitOfMeasure },
            { $Type: 'UI.DataField', Label: 'FNSKU', Value: YY1_FD_FNSKU },
            { $Type: 'UI.DataField', Label: 'SKU', Value: YY1_FD_SKU },
            { $Type: 'UI.DataField', Label: '对账口径', Value: YY1_FD_DZKB },
            { $Type: 'UI.DataField', Label: '生产开始日期', Value: ProductionStartDate },
            { $Type: 'UI.DataField', Label: '确认交货日期', Value: ConfirmedDeliveryDate },
            { $Type: 'UI.DataField', Label: '计划行订单数量', Value: ScheduleLineOrderQuantity },
            { $Type: 'UI.DataField', Label: '销售凭证拒绝原因', Value: SalesDocumentRjcnReason },
            { $Type: 'UI.DataField', Label: '业务流程ID', Value: zrfcid },
            { $Type: 'UI.DataField', Label: '多步ID', Value: zrfc_logid },
            { $Type: 'UI.DataField', Label: '多方交易类型ID', Value: zdfjy },
            { $Type: 'UI.DataField', Label: '消息状态', Value: code },
            { $Type: 'UI.DataField', Label: '消息文本', Value: message },
        ],
        Facets: [
            { $Type: 'UI.ReferenceFacet', Label: '基本信息', Target: '@UI.Identification' }
        ]
    }
);